hack/api-reference/config.json
hack/api-reference/registry.json

/area open-source
/kind cleanup
Updates kubernetes docs reference to 1.25
Part of https://github.com/gardener/gardener/issues/6911
```other operator
API reference documentation refers to kubernetes docs v1.25.
```

Update kubernetes docs reference to 1.25

---

.ci/component_descriptor
.ci/pipeline_definitions
.ci/prepare_release
.ci/verify

/area delivery
This PR adds pipeline definitions for release through Concourse.
Part of https://github.com/gardener/gardener-extension-registry-cache/issues/3
```other operator
NONE
```

Add pipeline definitions

---

.ci/pipeline_definitions
README.md

/area delivery
Currently the head-update job is building and pushing container images (see https://concourse.ci.gardener.cloud/teams/gardener/pipelines/gardener-extension-registry-cache-main/jobs/main-head-update-job/builds/1). This task is already tackled by prow (see https://prow.gardener.cloud/view/gs/gardener-prow/logs/post-gardener-extension-registry-cache-build-images/1615047981784895488). Hence, we don't want the concourse head-update job to publish container images (similar to the head-update job of gardener).
See above.
```other operator
NONE
```

Do not publish images in the head-update job

---

cmd/gardener-extension-registry-cache/app/app.go
go.mod
go.sum
pkg/cmd/options.go
pkg/controller/healthcheck/add.go
vendor/github.com/gardener/gardener/extensions/pkg/controller/healthcheck/actuator.go
vendor/github.com/gardener/gardener/extensions/pkg/controller/healthcheck/controller.go
vendor/github.com/gardener/gardener/extensions/pkg/controller/healthcheck/healthcheck_actuator.go
vendor/github.com/gardener/gardener/extensions/pkg/controller/healthcheck/inject.go
vendor/github.com/gardener/gardener/extensions/pkg/controller/healthcheck/message_util.go
vendor/github.com/gardener/gardener/extensions/pkg/controller/healthcheck/reconciler.go
vendor/modules.txt

/area control-plane
/kind bug
For the reasoning, please check https://github.com/gardener/gardener/issues/6775#issuecomment-1432816749 and https://github.com/gardener/gardener/pull/7660.
We need to add the healthcheck controller back and add `ShootSystemComponentsHealthy` to `conditionTypesToRemove`.
Part of  https://github.com/gardener/gardener/issues/6775
```bugfix operator
The stale healthcheck conditions from the `registry-cache` extension are now properly cleaned up.
```
```other dependency
The following dependency is updated:
- github.com/gardener/gardener: v1.65.0 -> v1.65.3
```

Vendor `gardener@1.65.3` and add `ShootSystemComponentsHealthy` to `conditionTypesToRemove`

---

charts/images.yaml

/area networking
This PR is needed to support IPv6 single stack and avoid DockerHub pull limits as it uses copied images from Gardener GCR instead.
Part of https://github.com/gardener/ci-infra/issues/619
```other operator
Switched images from DockerHub to copies in Gardener GCR
```

Switched from DockerHub to Gardener GCR

---

pkg/controller/criensurerdeployer.go
pkg/controller/registrydeployer.go

/area quality
/kind regression
/kind bug
Currently the cri-config-ensurer has the following code for the image:
https://github.com/gardener/gardener-extension-registry-cache/blob/0ef3e17b22d78bdd467af2b6392b00922b483c7a/pkg/controller/criensurerdeployer.go#L134
Note that it uses only the repository and ignores any tag.
This results in the Pod to be created such as:
```yaml
containers:
- name: name: cri-config-ensurer
image: eu.gcr.io/gardener-project/3rd/bash
```
After https://github.com/gardener/gardener-extension-registry-cache/pull/17, the repo is switched to `eu.gcr.io/gardener-project/3rd/bash` and the latest tag does no longer exists. Hence, currently the cri-config-ensurer cannot be pulled at all:
```
% k -n …
```

Fix cri-config-ensurer and registry images

---

.github/dependabot.yaml
.github/workflows/vendor_gardener.yaml

Similar to the other PRs from https://github.com/gardener/gardener/issues/6328
Part of https://github.com/gardener/gardener/issues/6328
N/A
```other operator
NONE
```

Enable dependabot for updating the `github.com/gardener/gardener` dependency

---

Makefile
test/e2e/common_test.go

/kind bug
Currently `make ci-e2e-kind` on a freshly cloned repo fails with:
```
touch: cannot touch 'hack/tools/bin/.version_skaffold_v2.2.0': No such file or directory
```
This PR is similar to https://github.com/gardener/gardener-extension-shoot-rsyslog-relp/pull/8.
This will hopefully fix the failing e2e-kind prow job.
See above.
N/A
```other operator
NONE
```

Add `hack/tools/bin/.gitkeep`. Fix `make extension-up`. Deflake the e2e tests

---

Makefile
go.mod

/kind bug
Currently dependabot fails with:
```
go: downloading go1.21 (linux/amd64)
go: download go1.21 for linux/amd64: toolchain not available
```
See https://github.com/dependabot/dependabot-core/issues/7895 and https://github.com/golang/go/issues/62278.
It seems that with go1.21 it is no longer possible to have `X.Y` as module version - see https://github.com/golang/go/issues/62278#issuecomment-1698829945.
N/A
N/A
```other operator
NONE
```

Use `1.21.0` instead of `1.21` as module version

---

pkg/component/registrycaches/registrycaches.go
pkg/component/registrycaches/registrycaches_test.go
pkg/constants/constants.go
pkg/controller/extension/actuator.go
test/e2e/common_test.go

/area metering
/area logging
Switch registry cache namespace from `registry-cache` to `kube-system`.
When registry cache stateful sets are deployed in `registry-cache` namespace into the `Shoot` cluster:
- no kubelet metrics for the `pods` (such as cpu/memory usage) and for the `volumes` (volume capacity and usage) metrics are be scraped.
- no logs from registry `pods` are be scraped.
Additionally, after https://github.com/gardener/gardener/pull/8483 we can no longer use the `registry-cache` Namespace. GRM fails because `registry-cache` is unknown namespace for cache:
```yaml
- lastTransitionTime: "2023-09-25T12:39:28Z"
lastUpdateTime: "2023-09-25T12:36:38Z"
message: 'error during apply of object …
```

Use `kube-system` namespace to deploy registry cache extension

---

.github/dependabot.yaml
.test-defs/TestSuiteRegistryCacheBetaSerial.yaml
test/common/common.go
test/e2e/common_test.go
test/e2e/create_enabled_hibernate_reconcile_delete_test.go
test/testmachinery/shoot/enable_disable_test.go
test/testmachinery/shoot/enable_hibernate_reconcile_wakeup_disable_test.go
test/testmachinery/shoot/shoot_suite_test.go

/area testing
This PR adds a testmachinery integration tests for the extension.
Initially, I tried to add an envtest for the controller but during Extension reconciliation we are creating a Shoot client and fetching the registry-cache Service IP to update them in the Extension status. Hence, envtest does not seem to be suitable. We can of course try to fake/mock the interaction with the Shoot kube-apiserver but then it won't be a real integration test.
That's why I decided to add a testmachinery test instead of envtest.
Part of https://github.com/gardener/gardener-extension-registry-cache/issues/3
N/A
```other …
```

Add testmachinery integration tests

---

pkg/component/registrycaches/registrycaches.go
pkg/component/registrycaches/registrycaches_test.go

Currently the registry Pods don't have a PriorityClass set:
```
% k -n registry-cache get po -o json | jq -c '.items[] | {name: .metadata.name, priority: .spec.priority}'
{"name":"registry-eu-gcr-io-0","priority":0}
{"name":"registry-quay-io-0","priority":0}
{"name":"registry-registry-k8s-io-0","priority":0}
```
This PR sets the PriorityClass to `system-cluster-critical`. See https://github.com/gardener/gardener/blob/v1.79.1/docs/development/priority-classes.md
The reasoning the choosing `system-cluster-critical` is:
> - When a request against the registry cache fails, containerd will retry the request against the upstream registry. When the registry cache is unavailable, a request times out in 30s …

Set `priorityClassName` for the registry cache Pods

---

pkg/component/registrycaches/registrycaches.go
pkg/component/registrycaches/registrycaches_test.go

This PR adds liveness and readiness probes to the registry Pods.
~~I was wondering which endpoint to use for the probes. There is `/debug/health` when debug is enabled  but it is not recommended for production environments (ref https://docs.docker.com/registry/configuration/#debug):~~
> Sensitive information may be available via the debug endpoint. Please be certain that access to the debug endpoint is locked down in a production environment.
~~I used `/` from after I inspired from an upstream chart (ref https://github.com/phntom/charts/blob/1927af1c70a919284241ed04669a566b39f675c2/docker-registry/templates/deployment.yaml#L57-L70).~~
See https://github.com/distribution/distribution/issues/4085#issueco …

Add readiness and liveness probe to the registry Pods

---

Makefile
hack/check-skaffold-deps.sh
skaffold.yaml

Currently, the ko builder does not detect changes to `go:embed` files (see https://github.com/GoogleContainerTools/skaffold/issues/7836). This makes impossible the development of some scripts that are used later by `go:embed`. This PR inspires from https://github.com/gardener/gardener/pull/6735 and https://github.com/gardener/gardener/pull/6781 and does the same setup for the registry-cache extension.
Part of #3
N/A
```other operator
NONE
```

skaffold: Rebuild when there are changes to `go:embed` files

---

pkg/admission/validator/helper.go
pkg/admission/validator/helper_test.go
pkg/admission/validator/shoot.go
pkg/admission/validator/shoot_test.go
pkg/apis/registry/helper/helper.go
pkg/apis/registry/helper/helper_test.go
pkg/apis/registry/validation/validation.go
pkg/apis/registry/validation/validation_test.go
skaffold.yaml

Currently we are using StatefulSet volumeClaimTemplate to provision the PVC. However the corresponding StatefulSet field that controls the PVC size is immutable. It is not possible to resize/enlarge the underlying PVC through the StatefulSet spec. See https://github.com/kubernetes/enhancements/issues/661 This commit makes the cache size field immutable until we decide how to implement the resize.
GRM currently does not try to update the `volumeClaimTemplates` of a StatefulSet as the field is immutable. See https://github.com/gardener/gardener/blob/292970d299b4a5b113c148fc23488b11542c8dd5/pkg/resourcemanager/controller/managedresource/merger.go#L284-L287. Hence, updating the cache's size via the Shoot …

Make the cache size field immutable

---

charts/admission/charts/runtime/templates/deployment.yaml
charts/admission/values.yaml

/area security
This PR adds the option to configure a projected volume for the validator which can be used as a kubeconfig. It is for example needed, if operators generate their kubeconfigs for the virtual garden cluster via the [TokenRequestor](https://github.com/gardener/gardener/blob/master/docs/concepts/resource-manager.md#tokeninvalidator-controller).
N/A
Similar to https://github.com/gardener/gardener-extension-provider-aws/pull/791
```other operator
NONE
```

Add support for projected volume kubeconfig

---

charts/admission/charts/runtime/templates/deployment.yaml

/kind cleanup
Right now the admission does not have a client and does not do requests against the virtual kube-apiserver or the runtime kube-apiserver. In future we might need to introduce such client (when validating the registry cache credentials) but currently the admission components don't need access to DNS, virtual kube-apiserver or runtime kube-apiserver.
N/A
N/A
```other operator
NONE
```

Address TODO related to admission Pod labels

---

test/common/common.go

/area testing
/kind bug
We have many e2e flakes of type:
```
[FAILED] Unexpected error:
<*errors.StatusError | 0xc0001519a0>: 
error dialing backend: dial tcp 10.2.2.180:9443: connect: connection refused
{
ErrStatus: {
TypeMeta: {Kind: "", APIVersion: ""},
ListMeta: {
SelfLink: "",
ResourceVersion: "",
Continue: "",
RemainingItemCount: nil,
},
Status: "Failure",
Message: "error dialing backend: dial tcp 10.2.2.180:9443: connect: connection refused",
Reason: "",
Details: nil,
Code: 500,
},
}
occurred
In [It] at: /home/prow/go/src/github.com/gardener/gardener-extension-registry-cache/test/common/common.go:107 @ 10/19/23 12:52:30.439
```
N/A
N/A …

Reduce e2e test flakes due to transient network errors

---

pkg/apis/registry/helper/helper_test.go
test/common/common.go
test/e2e/create_enable_add_remove_disable_delete_test.go
test/e2e/create_enabled_delete_shoot_system_components_test.go
test/e2e/create_enabled_hibernate_reconcile_delete_test.go
test/testmachinery/shoot/enable_disable_test.go
test/testmachinery/shoot/enable_hibernate_reconcile_wakeup_disable_test.go

/area testing
Currently we don't have a test where upstream addition and removal are tested. This PR covers this by extending the existing default e2e test.
N/A
N/A
```other operator
NONE
```

Extend the default e2e test to test upstream addition and removal

---

imagevector/images.yaml

The PR:
- excludes alpine and pause images from vulnerability scans
- updates alpine to 3.18.4
N/A
The PR depends on https://github.com/gardener/ci-infra/pull/990.
```other operator
Vulnerability scans are disabled for the alpine and pause images as the corresponding containers are not accessible from outside of the K8s clusters and not interacted with from other containers or other systems.
```
```other operator
The following image is updated:
- `eu.gcr.io/gardener-project/3rd/alpin`e: 3.15.8 -> 3.18.4
```

Skip vulnerability scans for the alpine and pause images

---

Dockerfile

Similar to https://github.com/gardener/gardener/pull/8628
N/A
N/A
```other developer
registyr-cache's base image is updated to `gcr.io/distroless/static-debian12:nonroot`.
```

Use debian 12 (bookworm) distroless image as base image

---

docs/development/extension-registry-cache.md
pkg/controller/extension/actuator.go
test/e2e/create_enable_force_delete_test.go

If the Shoot is in deletion, then there is no need to clean up the registry configuration from Nodes. The Shoot deletion flows ensures that the Worker is deleted before the Extension deletion. 
https://github.com/gardener/gardener/blob/6f8ce7692f793e583734f533cfdee7b9d93fb815/pkg/gardenlet/controller/shoot/shoot/reconciler_delete.go#L436-L440
The `deleteExtensionResourcesBeforeKubeAPIServer` step depends on `waitUntilManagedResourcesDeleted` which depends on `deleteManagedResources` which depends on `waitUntilWorkerDeleted`.
Hence, there are no Nodes, no need to clean up registry configuration.
N/A
N/A
```other …
```

Do not deploy the `registry-configuration-cleaner` on Shoot deletion

---

.dockerignore
Dockerfile
Makefile
cmd/gardener-extension-registry-cache-admission/app/app.go
cmd/gardener-extension-registry-cache/app/app.go
skaffold.yaml

This PR adopts the changes from https://github.com/gardener/gardener-extension-provider-openstack/pull/426 and https://github.com/gardener/gardener-extension-provider-openstack/pull/638 to the registry-cache extension.
With the v0.2.1 images:
```
%  docker run eu.gcr.io/gardener-project/gardener/extensions/registry-cache:v0.2.1 --version=raw
{"level":"error","ts":"2023-11-13T15:48:40.902Z","msg":"Error executing the main controller command","error":"unknown flag: --version","stacktrace":"main.main\n\t/go/src/github.com/gardener/gardener-extension-registry-cache/cmd/gardener-extension-registry-cache/main.go:32\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:267"}
% docker run …
```

Fix the `--version` flag

---

hack/check-skaffold-deps.sh

/kind bug
Obviously I fail to copy-paste. Reference source: https://github.com/gardener/gardener/blob/v1.83.2/hack/check-skaffold-deps.sh
Right now the script exits with 0 even when the skaffold config is outdated.
N/A
N/A
```other operator
NONE
```

Fix exit code handling for the `hack/check-skaffold-deps.sh` script

---

test/common/common.go
test/e2e/create_enabled_force_delete_test.go

Instead of creating the Shoot and then enabling the extension
Create the Shoot with enabled extension instead of creating the Shoot and then enabling the extension.
This should speed up the test a little bit.
N/A
N/A
```other operator
NONE
```

force deletion e2e test: Create the Shoot with enabled extension

---

skaffold.yaml

/kind cleanup
This PR runs `./hack/check-skaffold-deps.sh update` so that the skaffold file is updated according to the `./hack/check-skaffold-deps.sh` script.
N/A
N/A
```other operator
NONE
```

Nit: `./hack/check-skaffold-deps.sh update`

---

pkg/webhook/operatingsystemconfig/ensurer.go
pkg/webhook/operatingsystemconfig/ensurer_test.go
test/common/common.go

@rfranzke shared that there are issues with gardener-node-agent and our `configure-containerd-registries.service` unit. GNA restarts the unit, then it times out waiting the unit to be restarted (previously CCD was using the `--no-block` flag but the systemd go library does not support it):
```
Dec 06 14:19:27 iZgw8hgv2akgch5e5qsn13Z gardener-node-agent[3208]: {"level":"error","ts":"2023-12-06T14:19:27.387Z","msg":"Reconciler error","controller":"operatingsystemconfig","namespace":"kube-system","name":"gardener-node-agent-worker-1-f76b6","reconcileID":"772eff7b-9e6f-4f91-b51e-de49778d0e92","error":"failed executing unit commands: 1 error occurred:\n\t* unable to restart unit …
```

Switch the systemd unit type from `oneshot` to `simple`

---

pkg/component/registrycaches/registry_caches.go
pkg/controller/extension/actuator.go

/area control-plane-migration
/kind bug
Currently a CPM for a Shoot with registry-cache extension enabled fails during the migrate phase with:
```
task "Waiting until shoot managed resources have been deleted" failed: retry failed with context deadline exceeded, last error: retry failed with context deadline exceeded, last error: error while waiting for all shoot managed resources to be deleted: : 1 error occurred: shoot managed resource shoot--foo--bar/extension-registry-cache still exists
```
Right now in https://github.com/gardener/gardener/blob/628d9395e29f2fa285b5d825674ca3d8f5310fcc/pkg/gardenlet/controller/shoot/shoot/reconciler_migrate.go#L163-L168, gardenlet is taking care only for MRs with `origin=gardener`. …

Fix CPM for Shoot with registry-cache extension enabled

---

pkg/component/registrycaches/monitoring.go
pkg/component/registrycaches/monitoring/dashboard.json
pkg/component/registrycaches/monitoring/dashboard.yaml
pkg/component/registrycaches/registry_caches_test.go

/area monitoring
Add monitoring dashboard for registry cache persistent volumes
Part of #3
```feature operator
Metrics for registry cache persistent volumes are exposed in the `Registry caches` plutono dashboard.
```

Add monitoring dashboard for registry cache persistent volumes

---

test/common/common.go
test/e2e/create_enable_add_remove_disable_delete_test.go
test/e2e/create_enabled_force_delete_test.go
test/e2e/create_enabled_hibernate_reconcile_delete_test.go
test/testmachinery/shoot/enable_disable_test.go
test/testmachinery/shoot/enable_hibernate_reconcile_wakeup_disable_test.go

/area testing
/kind bug
The tests use `nginx:1.13.0` which is not a multi-arch image. 
The test execution against arm64 Shoots fails with:
```
In [It] at: /src/test/testmachinery/shoot/enable_disable_test.go:58 @ 12/20/23 07:30:11.546
}
},
s: "pod \"default/nginx-wfwb9\" is not ready: <nil>",
err: <*errors.errorString | 0xc000d3e4a0>{
ctxError: <context.deadlineExceededError>{},
{
retry failed with context deadline exceeded, last error: pod "default/nginx-wfwb9" is not ready: <nil>
<*retry.Error | 0xc0008188c0>: 
[FAILED] Expected success, but got an error:
/src/vendor/github.com/gardener/gardener/test/framework/gingko_utils.go:26
Shoot registry cache testing  [It] [BETA] [SERIAL] [SHOOT] should enable and disable the …
```

Fix the testmachinery test for arm64 Shoots

---

.ci/component_descriptor

/kind bug
Similar to https://github.com/gardener/gardener/pull/9008.
Currently the head-update job fails with:
```
Traceback (most recent call last):
File "<string>", line 438, in <module>
File "/usr/lib/python3.11/site-packages/gci/componentmodel.py", line 582, in from_dict
component_descriptor = dacite.from_dict(
^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/site-packages/dacite/core.py", line 64, in from_dict
value = _build_value(type_=field_type, data=field_data, config=config)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/site-packages/dacite/core.py", line 99, in _build_value
data = from_dict(data_class=type_, data=data, config=config) …
```

Set COMPONENT_PREFIXES env var to fix component descriptor step in the head-update job

---

pkg/component/registrycaches/registry_caches_test.go
pkg/component/registrycaches/templates/config.yml.tpl

/kind bug
We have occurrences of https://github.com/distribution/distribution/issues/4191 (duplicate of https://github.com/distribution/distribution/issues/2367) in our environments. The issue can be mitigated by disabling the blobdescriptor cache. See https://github.com/distribution/distribution/issues/2367#issuecomment-1874449361.
Part of #3 
N/A
```other operator
An issue in the [Distribution project](https://github.com/distribution/distribution/) that causes in-used blob to be wrongly deleted during GC of an image layer which later on causes the images that reference this blob to fail to be pulled is now mitigated.
```

Mitigate distribution/distribution#4191 by disabling blobdescriptor cache

---

docs/usage/configuration.md
hack/api-reference/registry.md
pkg/admission/validator/shoot_test.go
pkg/apis/registry/v1alpha1/types.go
pkg/apis/registry/v1alpha2/types.go
pkg/apis/registry/validation/validation.go
pkg/apis/registry/validation/validation_test.go
pkg/component/registrycaches/registry_caches.go

While working on https://github.com/gardener/gardener-extension-registry-cache/pull/129 I noticed that we actually don't support upstreams with ports but our docs state that it is supported.
A Shoot reconciliation with a cache with upstream with a port (for example `public.ecr.aws:443`) fails with:
```
v1/Secret/kube-system/registry-public-ecr-aws-config-3cfbb538\": Secret \"registry-public-ecr-aws-config-3cfbb538\" is invalid: metadata.labels: Invalid value: \"public.ecr.aws:443\": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is …
```

Improve the validation for a cache upstream

---

docs/usage/configuration.md
pkg/apis/registry/validation/validation.go
pkg/apis/registry/validation/validation_test.go

While looking into the GC in the Distribution project I noticed https://github.com/distribution/distribution/issues/4249. Long story short, once you enable GC for a cache with disabled GC, images that were pulled before `7d` in the cache with disabled GC will never be GC-ed. This can be confusing for users as usually the expectation would be that once GC is enabled, all images to get GC-ed after the TTL (`7d`) is expired.
Part of #3
N/A
```breaking user
It is now forbidden to enable garbage collection for a cache once it is disabled. This constraint is added to mitigate …
```

Forbid GC enablement once it is disabled

---

pkg/component/registrycaches/export_test.go
pkg/component/registrycaches/registry_caches.go
pkg/component/registrycaches/registry_caches_test.go

/area quality
/kind bug
The reason for #120 is https://github.com/kubernetes/kubernetes/issues/64023. Long story short the explanation is:
```golang
// The StatefulSet name limit is 63 chars. However Pods for a StatefulSet with name > 52 chars cannot be created due to https://github.com/kubernetes/kubernetes/issues/64023.
// The "controller-revision-hash" label gets added to the StatefulSet Pod. The label value is in format <stateful_set_name>_<hash> where <hash> is 10 or 11 chars.
```
With this PR we mitigate the upstream issue by NOT exceeding 52 chars for StatefulSet names. This change should be backwards-compatible.
Fixes #120
For completeness, …

Fix StatefulSet Pod creation for caches with a long upstream

---

pkg/admission/validator/cache/shoot_test.go
pkg/admission/validator/mirror/shoot_test.go
pkg/webhook/cache/ensurer_test.go
test/common/common.go
test/e2e/cache/create_enable_add_remove_disable_delete.go
test/e2e/cache/create_enabled_delete_shoot_system_components.go
test/e2e/cache/create_enabled_force_delete.go
test/e2e/cache/create_enabled_hibernate_reconcile_delete.go
test/testmachinery/shoot/enable_disable_test.go
test/testmachinery/shoot/enable_hibernate_reconcile_wakeup_disable_test.go

/kind cleanup
This PR is a preparation for the v1alpha1 API removal.
Part of #3
N/A
```other operator
NONE
```

Clean up v1alpha1 usages from tests

---

pkg/component/registrycaches/monitoring.go
pkg/component/registrycaches/monitoring/dashboard.json
pkg/component/registrycaches/registry_caches_test.go

/area monitoring
Add scrape configuration and monitoring dashboard 
Part of #3 
```feature operator
Panels for the registry caches are now available in `Registry Caches` plutono dashboard.
```

Add scrape config and monitoring dashboard

---

imagevector/images.yaml

Docs: https://pages.github.tools.sap/kubernetes/compliance-reporting/cvss-rescoring.html#cvss-categorisation
N/A
N/A
```other operator
NONE
```

Add CVE categorisation for the registry image

---

.ci/third_party/component_descriptor
.ci/third_party/prepare_release
docs/usage/registry-cache/configuration.md
docs/usage/registry-cache/upstream-credentials.md

This PR improves the upstream credentials docs by described how generally things work in K8s (without registry cache) and what is the limitation in the Distribution project that forces the people to provide their credentials one more time (for the registry cache).
Part of #3
N/A
```other operator
NONE
```

Improve the upstream credentials docs

---

docs/development/extension-registry-cache.md
docs/development/getting-started-locally.md
docs/usage/registry-cache/configuration.md
docs/usage/registry-cache/migration-from-v1alpha2-to-v1alpha3.md
docs/usage/registry-cache/upstream-credentials.md
docs/usage/registry-mirror/configuration.md

/area documentation
All links to documents in [gardener/gardener](https://github.com/gardener/gardener) are changed to point to master branch. In this way the links in the https://gardener.cloud/docs/ will be relative internal links and will no longer point to github. 
Fixes #
N/A
```other operator
NONE
```

Fix links to gardener/gardener docs

---

pkg/component/registrycaches/registry_caches_test.go
pkg/component/registrycaches/templates/config.yml.tpl

/area robustness
Sets registry `http.draintimeout` configuration option to 25 seconds. After registry process receives SIGTERM signal, it will gracefully shuts down the server and wait 25 sec for active connections to drain.
Part of #3 
```other operator
Registry configuration option `http.draintimeout` is set to 25 seconds to activate registry graceful shutdown.
```

Activate registry graceful shutdown

---

pkg/admission/validator/cache/shoot_test.go
pkg/admission/validator/mirror/shoot_test.go
pkg/controller/cache/actuator.go
pkg/webhook/cache/ensurer_test.go
test/common/common.go
test/e2e/cache/create_enable_add_remove_disable_delete.go
test/e2e/cache/create_enabled_delete_shoot_system_components.go
test/e2e/cache/create_enabled_force_delete.go
test/e2e/cache/create_enabled_hibernate_reconcile_delete.go
test/testmachinery/shoot/enable_disable_test.go
test/testmachinery/shoot/enable_hibernate_reconcile_wakeup_disable_test.go

/kind cleanup
This PR is a preparation for the v1alpha2 API removal.
Part of #3
N/A
```other operator
NONE
```

Clean up v1alpha2 usages

---

pkg/component/registrycaches/alerting-rules/registry-cache.rules.yaml

/area monitoring
This PR adds recording rules to federate the `registry_proxy_pushed_bytes_total`, `registry_proxy_pulled_bytes_total` metrics in the Seed cluster's aggregate prometheus and in then also in the prometheus in the runtime cluster.
The motivation for this PR is that currently it is not possible to fetch check the above-mentioned metrics for several clusters. We only have the `Registry Cache` dashboard and we display the "delta" (pushed to clients - pulled from upstream) there. However, to conclude on the improvements by the registry-cache extensions, it would be nice to be able to fetch the metrics for given set of Shoots. For example, to be able to do queries like: fetch the "delta" for …

Add recording rules that will be federated by aggregate prometheus and garden-prometheus

---

go.mod

Right now, dependabot fails to create a version bump for gardener/gardener with:
```
updater | 2024/04/09 19:08:47 INFO <job_812251957> Handled error whilst updating github.com/gardener/gardener: dependency_file_not_resolvable {:message=>"go: loading module retractions for github.com/gardener/gardener@v0.32.0: module github.com/gardener/gardener@v1.92.0 requires go >= 1.22.2 (running go 1.22.1; GOTOOLCHAIN=local+auto)"}
```
In https://github.com/gardener/gardener-extension-registry-cache/pull/177, I missed to update the go module version to go 1.22.2.
When you bump the gardener/gardener version to v1.92.0 locally and then run `make tidy`, the go tool is able to deal with it and to upgrade the module …

Upgrade the module version to 1.22.2

---

pkg/component/registrycaches/export_test.go
pkg/component/registrycaches/registry_caches.go
pkg/component/registrycaches/registry_caches_test.go

/area quality
The value of labels in Kubernetes is limited to 63 chars. The value of the `upstream-host` label is used to construct the registry cache resource names (`registry-<escaped-upstream-host-value>`) and for the StatefulSet name the limit is 52 (see #129) . To use a uniform value for both labels and component names, the `upstream-host` label value is limited to 43 chars.
Currently the remote registry host (`caches[].upstream`) is used for `upstream-host` label value. If this value is longer than 43 chars it is transformed to `<truncated-upstream>-<hash>` where `<truncated-upstream>` is the upstream truncated to 37 char and `<hash>` is the first 5 chars of `upstream` SHA256.
**Which issue(s) …

Limit upstream-host label value to 43 chars

---

.github/dependabot.yaml

With this change dependabot should add the kind/enhancement label automatically. Currently, we have to add it manually always, for example see https://github.com/gardener/gardener-extension-registry-cache/pull/191#issuecomment-2100172880. This repo is managed by prow and the kind label is required by prow.
N/A
N/A
```other operator
NONE
```

Add the kind/enhancement label to the dependabot PRs

---

test/common/common.go
test/e2e/cache/create_enable_add_remove_disable_delete.go
test/e2e/cache/create_enabled_delete_shoot_system_components.go
test/e2e/cache/create_enabled_force_delete.go
test/e2e/cache/create_enabled_hibernate_reconcile_delete.go
test/testmachinery/shoot/enable_disable_test.go
test/testmachinery/shoot/enable_hibernate_reconcile_wakeup_disable_test.go

/area testing
/kind test
Rework the image pull check in E2E tests.
The image pull check now use root pod executor and runs the following commands on the Node where the registry Pod is running:
- `jq -j '.mounts[] | select(.destination=="/var/lib/registry") | .source' /run/containerd/io.containerd.runtime.v2.task/k8s.io/<registry-container-id>/config.json` to get the location of '/var/lib/registry' mount on the Node.
- `cat <mount-location>/docker/registry/v2/repositories/<image-path>/_manifests/tags/<image-tag>/current/link` to get the image index blob location.
- `jq -j '.manifests | length' %s/docker/registry/<image-index-blob-path>/blobs/%s/data` to verify it is valid image index.
This will allow `distroless` to be …

Rework image pull check in E2E tests

---

pkg/component/registrycaches/registry_caches.go
pkg/component/registrycaches/registry_caches_test.go

/kind cleanup
Removes the `DeleteOnInvalidUpdate` annotation as registry cache StatefulSets for registries with `upstream` host with more than 43 chars are already recreated.
Ref: #186 
Fixes #
N/A
```other operator
NONE
```

Remove the `DeleteOnInvalidUpdate` annotation

---

docs/usage/registry-cache/upstream-credentials.md
pkg/admission/validator/cache/shoot.go
pkg/admission/validator/cache/shoot_test.go

/area ops-productivity
Adds validation early exit when no semantic change in providerConfig is detected. This way the redundant validation checks are skipped, the performance is improved and the possibility of blocking reconciliation or deleting the Shoot is minimized.
Fixes #
N/A
```other operator
The registry-cache admission validation is skipped when no semantic change in `providerConfig` is detected.
```

Add validation early exit when no semantic change in providerConfig is detected

---

.test-defs/TestSuiteRegistryCacheBetaSerial.yaml
hack/test-e2e-local.sh

/area testing
ginkgo's default timeout is `1h`:
```
--timeout [duration] (default: 1h)
Test suite fails if it does not complete within the specified timeout.
```
Running `make test-e2e-local PARALLEL_E2E_TESTS=1` locally is likely to time out:
```
Summarizing 1 Failure:
[TIMEDOUT] Registry Cache Extension Tests [It] should create Shoot, enable extension, add upstream, remove upstream, disable extension, delete Shoot [cache]
/go/src/github.com/gardener/gardener-extension-registry-cache/test/e2e/cache/create_enable_add_remove_disable_delete.go:27
Ran 5 of 5 Specs in 3588.601 seconds
FAIL! - Suite Timeout Elapsed -- 4 Passed | 1 Failed | 0 Pending | 0 Skipped
--- FAIL: TestE2E (3588.60s)
FAIL
Ginkgo ran …
```

e2e && tm tests: Increase ginkgo timeouts

---

test/common/common.go
test/e2e/cache/create_enable_add_remove_disable_delete.go
test/e2e/cache/create_enabled_force_delete.go
test/e2e/cache/create_enabled_hibernate_reconcile_delete.go
test/testmachinery/shoot/enable_disable_test.go
test/testmachinery/shoot/enable_hibernate_reconcile_wakeup_disable_test.go

/area testing
The prow CI runs e2e tests on each PR and this results in 6 image pulls from docker.io. .Since docker hub's pull limit is 100 downloads per 6 hours per IP address, we more often see a `You have reached your pull rate limit` error, causing PR checks to fail. To reduce docker hub image pull, `docker.io` is replaced by `public.ecr.aws` registry.
N/A
To avoid conflicts with registries in local setup [Drop registry caches for eu.gcr.io and ghcr.io](https://github.com/gardener/gardener/pull/10185) PR should be merged first.
```other operator
NONE
```

Replace use of `docker.io` with `public.ecr.aws` to avoid docker hub pull rate limit errors

---

docs/usage/registry-cache/configuration.md

/area documentation
This PR fixes a broken link in the documentation. The resource has been removed in https://github.com/gardener/gardener-extension-registry-cache/pull/237
Fixes #
```doc developer
NONE
```

Fixed broken links - 2024.08

---

docs/usage/registry-cache/configuration.md
test/common/common.go
test/e2e/cache/create_enable_add_remove_disable_delete.go
test/e2e/cache/create_enabled_delete_shoot_system_components.go
test/e2e/cache/create_enabled_force_delete.go
test/e2e/cache/create_enabled_hibernate_reconcile_delete.go
test/testmachinery/shoot/enable_disable_test.go
test/testmachinery/shoot/enable_hibernate_reconcile_wakeup_disable_test.go

/area testing
/kind flake
There is an [issue](https://github.com/distribution/distribution/issues/4383) when `distribution/distribution` is used as a pull-through cache to Amazon Public ECR Gallery. Sometimes image manifests are successfully cached, but download of image layers blobs fails with `Internal Server Error - 500`. 
With this PR `public.ecr.aws/nginx/nginx` image is replaced with `ghcr.io/jitesoft/alpine`. The `VerifyRegistryCache` func is extended to support various images.
N/A
N/A
```other operator
NONE
```

Replace use of `public.ecr.aws/nginx/nginx` with `ghcr.io/jitesoft/alpine` image

---

.ci/pipeline_definitions

/area delivery
/kind cleanup
After https://github.com/gardener/gardener-extension-registry-cache/pull/229 we noticed that we unnecessary build and push images and charts on pull requests. This PR adapts the extension to be like the gardener/gardener repo: there is already a prow job on PRs and builds the images without pushing it.
N/A
N/A
```other operator
NONE
```

pipeline_definitions: Don't build and push images and charts on pull requests

---

Makefile

Locally, I hit the following issue. I executed `make extension-down` while I still had a Shoot with enabled `registry-cache` extension. The admission helm chart was deleted by `make extension down` which under the hood runs `skaffold delete`. But the admission webhook was still present in the system (not part of the chart) and was blocking updates of the Shoot because there was no admission Pod running anymore. 
After https://github.com/gardener/gardener-extension-registry-cache/pull/122 the validating webhook is no longer part of the admission chart but it is created on admission Pod startup. Hence, we have to delete it explicitly.
N/A …

make extension-down: Delete the validating webhook of the admission component

---

test/common/common.go

/area testing
Improves image pull check with following:
- extract the image manifest for Node architecture from the index file
- extract all image layers from the manifest
- ensure that all image layers data files exist in the registry storage  
N/A
N/A
```other operator
NONE
```

Improve image pull check

---

example/shoot-registry-cache.yaml
example/shoot-registry-mirror.yaml

/kind cleanup
The annotation was removed in Gardener v1.94.0 with https://github.com/gardener/gardener/pull/9632.
N/A
N/A
```other operator
NONE
```

Clean up usages of the already removed `shoot.gardener.cloud/infrastructure-cleanup-wait-period-seconds` annotation

---

Makefile
skaffold.yaml

/kind bug
See https://github.com/gardener/gardener-extension-registry-cache/issues/278
Fixes https://github.com/gardener/gardener-extension-registry-cache/issues/278
```bugfix developer
An issue causing `make extension-up` to do NOT generate a new tag for local source code changes is now fixed.
```

Fix skaffold tag generation to generate a new tag on code changes (without local commit)

---

skaffold.yaml

/kind bug
See more details in https://github.com/gardener/gardener-extension-registry-cache/issues/276 and in the comment in the `skaffold.yaml` file.
Fixes https://github.com/gardener/gardener-extension-registry-cache/issues/276
N/A
```bugfix developer
An issue causing `make extension-up` to fail to patch the ControllerDeployment is now mitigated.
```

Fix `make extension-up`

---

.ci/pipeline_definitions
.gitignore
Makefile

/area compliance
This PR enables gosec following https://github.com/gardener/gardener-extension-shoot-rsyslog-relp/pull/189
Fixes https://github.com/gardener/gardener-extension-registry-cache/issues/269
```other developer
`gosec` is made available for SAST(static application security testing). It can be run with `make sast` or `make sast-report`, but is also incorporated in the `verify` and `verify-extended` makefile targets. 
```

Enable gosec for static application security testing

---

skaffold.yaml

/kind cleanup
In https://github.com/gardener/gardener-extension-shoot-rsyslog-relp/pull/194#discussion_r1848606461 @plkokanov found that we don't need a custom `tagPolicy` for the admission.
Follow-up after https://github.com/gardener/gardener-extension-registry-cache/pull/279
N/A
```other operator
NONE
```

skaffold: Remove custom `tagPolicy` for the admission

---

test/e2e/cache/create_enabled_delete_shoot_system_components.go

/area testing
/kind flake
Increase the context timeout of `Create Shoot` step in `e2e-cache-ssc` e2e test to 15 minutes.
Mitigate #290 
N/A
```other operator
NONE
```

Increase the `e2e-cache-ssc` e2e test create shoot context timeout to 15 minutes

---

pkg/component/registrycaches/registry_caches.go
pkg/component/registrycaches/registry_caches_test.go
test/e2e/cache/create_enable_for_private_registry_delete.go
test/e2e/common.go

/area testing
The `managedResourceObjectsMatcher` is introduced with https://github.com/gardener/gardener/pull/9964 in `gardener/gardener@v1.98.0`. We had an item in our backlog to evaluate it and potentially start using it.
The managedResourceObjectsMatcher:
- reduces some boilerplate - we no longer need to fetch the ManagedResource Secret, then uncompress and decode it to fetch the manifest inside
- we can pass native go types for the expected resources instead of serialized YAML manifests. The YAML manifests are sensitive to whitespace and key order.
N/A
N/A
```other operator
NONE
```

Rework the component unit tests to use the managedResourceObjectsMatcher

---

.ci/third_party/component_descriptor

`.ci/component_descriptor` was copied into this repository from https://github.com/gardener/gardener.
Historically, the file used to be vendored into muliple repositories and thus needed to support
different repository-layouts. This is no longer the case, as vendoring was dropped some time back.
Rm unused codepath as cleanup (will help migrating from Concourse-Pipeline-Template).
/area delivery
/kind cleanup
```other developer
NONE
```

cleanup: drop unused codepath

---

docs/usage/registry-cache/configuration.md

/kind cleanup
Right now, the `А` in https://github.com/gardener/gardener-extension-registry-cache/blob/4b9368c6f417fd6bf383d7965b8350aaafde503d/docs/usage/registry-cache/configuration.md?plain=1#L146 is the cyrillic `А` and not the English one. This PR fixes it to use the English `A`.
Introduced with https://github.com/gardener/gardener-extension-registry-cache/commit/9176c6572d582e0725024b1db30735d8c7f25cbc (cc @n-boshnakov).
N/A
N/A
```other operator
NONE
```

Fix a cyrillic character in the header

---

pkg/cmd/options.go
pkg/controller/cache/actuator.go
pkg/webhook/cache/ensurer.go
pkg/webhook/mirror/ensurer.go

/area quality
Similar to https://github.com/gardener/gardener-extension-shoot-rsyslog-relp/pull/209
N/A
N/A
```other operator
NONE
```

Make decoding of `Raw` to configs consistent

---

pkg/component/registrycaches/registry_caches_test.go
pkg/controller/cache/actuator.go

/area quality
/kind bug
We found that we have a race during the non-TLS to TLS migration.
In order to move the registry-cache Services from the `extension-registry-cache` MR to the `extension-registry-cache-services` MR, we patch the MR status to remove the Services from the `extension-registry-cache` MR status: https://github.com/gardener/gardener-extension-registry-cache/blob/f614b47ce02c1c21cb19316229113ae5bdaf6333/pkg/controller/cache/actuator.go#L76-L81
However, it might be the case that after this operation and before we update the desired resources in the e `extension-registry-cache` MR, the MR is reconciled by the GRM (syncPeriod=1min).
If this happens, removal of the Services from the …

Fix a corner case in the non-TLS to TLS registry-cache migration

---

.github/dependabot.yaml

We don't want dependabot PRs for golang release candidate (rc) versions. Examples:
- https://github.com/gardener/gardener-extension-registry-cache/pull/332
- https://github.com/gardener/gardener-extension-registry-cache/pull/333
N/A
N/A
```other operator
NONE
```

dependabot: Ignore go rc versions

---

pkg/secrets/config.go

/area security
/kind bug
The registry cache service DNS names are included in `Subject Alternative Name` of the server certificate. This will allow 
access to the registry cache using the service name (as in the `prow` use case).
The service's ClusterIP is no longer converted to IPv4 to support IPv6 as well. 
Fixes #
```other operator
The registry cache DNS service names are now included in the `Subject Alternative Name` of the server certificate.
```
```other operator
Registry cache Services with IPv6 `spec.clusterIP` are now supported.
```

Add DNS service names in secret config

---

pkg/component/registrycaches/registry_caches.go
pkg/component/registrycaches/registry_caches_test.go
pkg/secrets/config.go
pkg/secrets/config_test.go
pkg/utils/registry/registry.go
pkg/utils/registry/registry_test.go

/area quality
/kind bug
See https://github.com/gardener/gardener-extension-registry-cache/issues/337.
This PR uses the same name (suffixed with `-tls`) which is used for the StatefulSet and the other resources. 
Fixes https://github.com/gardener/gardener-extension-registry-cache/issues/337
N/A
```bugfix user
An issue causing reconciliation to fail for caches with long upstreams (> 59 chars) is now fixed.
```

Fix reconciliciation for a cache with a long upstream

---

.dockerignore
pkg/component/registrycacheservices/registry_cache_services.go
pkg/component/registrycacheservices/registry_cache_services_test.go
pkg/controller/cache/actuator.go
pkg/controller/cache/add.go
skaffold.yaml
third_party/gardener/gardener/pkg/utils/managedresources/managedresources.go

/area quality
/kind bug
In https://github.com/gardener/gardener-extension-registry-cache/blob/d37f25b4940de579955fd1b3e42503f2ee524182/pkg/controller/cache/actuator.go#L89-L95 the following race happens: The `Wait` call succeeds right away because it acts on outdated ManagedResource version. A cached client is being used and it is not yet updated the local cache with the later revision of the ManagedResource that contains the updates after the `Deploy` func.
With this PR, we aim to address this race by using a direct client which will always read the ManagedResource from the kube-apiserver.
Hence, we should not act on outdated revision of the ManagedResource resource.
Fixes #343 …

Fix a race condition that could occur while switching between TLS enabled and disabled

---

test/common/common.go
test/e2e/cache/create_disable_tls_enable_tls_delete.go
test/e2e/cache/create_enable_add_remove_disable_delete.go
test/e2e/cache/create_enable_for_private_registry_delete.go
test/e2e/cache/create_enabled_force_delete.go
test/e2e/cache/create_enabled_hibernate_reconcile_delete.go
test/testmachinery/shoot/enable_disable_test.go
test/testmachinery/shoot/enable_hibernate_reconcile_wakeup_disable_test.go
test/testmachinery/shoot/enable_rotate_ca_disable_test.go

/area testing
See https://github.com/gardener/gardener-extension-registry-cache/issues/328.
Fixes https://github.com/gardener/gardener-extension-registry-cache/issues/328
N/A
```other operator
NONE
```

tests: Do not wait 30s for the alpine Pod to be deleted

---

test/e2e/cache/create_enabled_force_delete.go

/area testing
See https://github.com/gardener/gardener-extension-registry-cache/issues/338
Fixes https://github.com/gardener/gardener-extension-registry-cache/issues/338
The used registry requires credentials for image pulling. That's why the verification that the cache is working for this e2e test is removed.
```other operator
NONE
```

e2e: Use a cache with a long upsteam in the force deletion e2e test

---

.github/dependabot.yaml

/kind cleanup
This reverts commit ecc66b7528aa3cc88fe4dd505b8b517b6b88842c.
Even after the try to fix it in https://github.com/gardener/gardener-extension-registry-cache/pull/335, https://github.com/gardener/gardener-extension-registry-cache/network/updates still fails with:
```
The property '#/updates/1/ignore/0/versions' includes invalid version requirements for a docker ignore condition
The property '#/updates/2/ignore/0/versions' includes invalid version requirements for a docker ignore condition
```
While dependabot still somehow continues to work despite this error (see created PRs https://github.com/gardener/gardener-extension-registry-cache/pull/341 and …

Revert "dependabot: Ignore go rc versions"

---

Makefile

/kind bug
Similar to https://github.com/gardener/gardener-extension-shoot-rsyslog-relp/pull/236
Introduced with https://github.com/gardener/gardener-extension-registry-cache/pull/279.
N/A
N/A
```bugfix developer
Fixed an issue that caused skaffold to fail to tag the `gardener-extension-shoot-rsyslog-relp` image during the execution of the `make remote-extension-up` command.
```

Fix tagging of extension image for remote dev setup

---

test/e2e/common.go

/area testing
We now and then see flakes in the e2e tests. See #283.
I was not able yet to reproduce the flakes from #283 but as we talked offline, disabling the VPA for the e2e test Shoots makes sense.
In a local run of the test, VPA eviction happen few seconds after the test Pod was created (and its image was pulled by the registry cache).
Event:
```yaml
- apiVersion: v1
count: 1
eventTime: null
firstTimestamp: "2025-02-12T15:52:48Z"
involvedObject:
apiVersion: v1
kind: Pod
name: registry-ghcr-io-0
namespace: kube-system
resourceVersion: "1883"
uid: 27f85490-5cfc-4e28-8e92-c22c5b916b2e
kind: Event
lastTimestamp: "2025-02-12T15:52:48Z"
message: Pod was evicted by VPA Updater to apply resource …
```

e2e tests: Disable VPA for the e2e test Shoots

---

test/e2e/cache/create_enable_for_private_registry_delete.go
test/e2e/cache/create_enabled_delete_shoot_system_components.go

/area testing
/kind flake
Improving the check for Node bootstrap issue. Now containerd logs are checked for I/O timeout errors during image pull.
Fixes #290 
Depends on https://github.com/gardener/gardener/pull/11010 and/or https://github.com/gardener/gardener/pull/11008
```other operator
NONE
```

Improve the check for Node bootstrap issue

---

.test-defs/TestSuiteRegistryCacheSerial.yaml
test/testmachinery/shoot/enable_disable_test.go
test/testmachinery/shoot/enable_hibernate_reconcile_wakeup_disable_test.go
test/testmachinery/shoot/enable_rotate_ca_disable_test.go

/area testing
Similar to https://github.com/gardener/gardener-extension-shoot-rsyslog-relp/pull/217 and https://github.com/gardener/gardener-extension-shoot-rsyslog-relp/pull/235.
N/A
N/A
```other developer
The registry-cache extension test-machinery tests are no longer beta.
```

Promote `testmachinery` tests to GA

---

pkg/component/registrycaches/registry_caches.go
pkg/component/registrycaches/registry_caches_test.go

/area quality
/kind bug
The registry cache StatefulSet is annotated with `reference.resources.gardener.cloud/secret-<hash>` annotation for config and TLS secrets. This will prevent garbage collection of secrets that are still in use.
The custom checksum annotation is removed from the StatefulSet's Pod template as it is no longer needed.
Fixes #362 
N/A
```bugfix operator
An issue where the referenced registry-cache config or TLS Secret is being garbage collected while it is still in-use has been fixed.
```

Annotate registry cache StatefulSet with the `reference.resources.gardener.cloud/secret-<hash>` annotation 

---

.reuse/dep5

/kind cleanup
```
The following files have no copyright and licensing information:
* skaffold-operator.yaml
```
Follow-up after https://github.com/gardener/gardener-extension-registry-cache/pull/361
N/A
```other operator
NONE
```

Fix reuse compliance

---

Makefile
skaffold-operator.yaml
skaffold.yaml

/kind cleanup
See https://github.com/gardener/gardener-extension-shoot-rsyslog-relp/pull/242#pullrequestreview-2660854875
With https://github.com/gardener/gardener-extension-registry-cache/issues/278, we introduced a custom `tagPolicy`.
After https://github.com/gardener/gardener-extension-registry-cache/pull/357, we no longer need it as we no longer make use of the `SKAFFOLD_IMAGE` env var.
Follow-up after https://github.com/gardener/gardener-extension-registry-cache/pull/357
N/A
```other operator
NONE
```

skaffold: Clean up no longer needed custom `tagPolicy`

---

charts/admission/charts/runtime/templates/service.yaml

/area networking
/area high-availability
See more details in https://github.com/gardener/gardener/issues/10421 and https://github.com/gardener/gardener/pull/11178.
Part of https://github.com/gardener/gardener/issues/10421
N/A
```other operator
The [`ServiceTrafficDistribution`](https://kubernetes.io/docs/reference/networking/virtual-ips/#traffic-distribution) feature is being used on to make Services topology-aware when the runtime Kubernetes version is 1.31+.
```

Use ServiceTrafficDistribution to make Services topology-aware when runtime Kubernetes >= 1.31

---

docs/usage/registry-cache/configuration.md
hack/api-reference/registry.md
pkg/apis/registry/types.go
pkg/apis/registry/v1alpha3/types.go
pkg/component/registrycaches/registry_caches.go
pkg/component/registrycaches/registry_caches_test.go

/area high-availability
I had cosmetic review suggestions on #298.
I am not allowed to push to StackIT repo, that's why I decided to lgtm + approve #298 so that it is finally merged. And I raised this PR to address the cosmetic suggestions.
Follow-up after #298 
N/A
```other operator
NONE
```

Address PR review suggestions for #298

---

pkg/component/registrycaches/registry_caches.go
pkg/component/registrycaches/registry_caches_test.go

/area auto-scaling
This PR removes maxAllowed from the registry cache VPA.
We see occurrences where the registry has to consume more than 8Gi (filesystem page caches). We saw memory usage of 12Gi dropped to 1Gi after the kernel OOM killer was invoked which also cleared all the page cache memory. 
I was not able to reproduce such behaviour in a test environment in the same scale - registry cache having a high and constant memory usage due to active page cache. 
Previously, maxAllowed was used in Gardener components to prevent vpa-recommender issuing recommendations that make the Pod unschedulable (see https://github.com/kubernetes/autoscaler/issues/7147). However, in VPA 1.4.0 it will be possible to …

Remove maxAllowed from the registry cache VPA

---

pkg/apis/registry/helper/helper.go
pkg/apis/registry/helper/helper_test.go
pkg/component/registrycaches/registry_caches.go
pkg/component/registrycaches/registry_caches_test.go

/area high-availability
According to [High Availability docs](https://github.com/gardener/gardener/blob/v1.118.0/docs/development/high-availability-of-components.md#convenient-application-of-these-rules):
> 2. All components should be generally equipped with `PodDisruptionBudget`s with `.spec.maxUnavailable=1` and `unhealthyPodEvictionPolicy=AlwaysAllow`
This especially makes sense when running a registry cache with HA enabled (2 replicas):
- A PodDistruptionBudget will prevent eviction of the registry-cache Pod if the other replica is unhealthy.
- During rolling updates of the registry cache StatefulSet, it will prevent both of the registry cache replicas to be unhealthy at the same time.
**Which …

Add PodDistruptionBudget when HA is enabled

---

test/testmachinery/shoot/enable_disable_test.go
test/testmachinery/shoot/enable_hibernate_reconcile_wakeup_disable_test.go
test/testmachinery/shoot/enable_rotate_ca_disable_test.go

/area testing
We see and in some cases, previous executions of TM tests leave the TM Shoot in hibernated state.
When our TM tests are executed against such hibernated Shoot, they fail with:
```
• [PANICKED] [122.661 seconds]
Shoot registry cache testing  [It] [SERIAL] [SHOOT] should enable and disable the registry-cache extension
/go/pkg/mod/github.com/gardener/gardener@v1.115.1/test/framework/gingko_utils.go:16
[PANICKED] Test Panicked
In [It] at: /usr/local/go/src/runtime/panic.go:262 @ 05/08/25 01:15:14.268
runtime error: invalid memory address or nil pointer dereference
Full Stack Trace
github.com/gardener/gardener-extension-registry-cache/test/common.VerifyRegistryCache({0x2b7f8b8, 0xc000371110}, …
```

tm tests: Add expectation framework's Shoot client not to be nil

---

.ci/third_party/component_descriptor

/area delivery
/kind cleanup
Incorporate the changes from https://github.com/gardener/gardener/pull/12173.
N/A
N/A
```other operator
NONE
```

Sync `.ci/third_party` scripts

---

.github/workflows/build.yaml

/area delivery
/kind bug
Fix the name of the admission application chart.
Follow-up after https://github.com/gardener/gardener-extension-registry-cache/pull/420
/cc @ialidzhikov 
```other operator
NONE
```

Fix the name of the admission application chart

---

docs/usage/registry-cache/configuration.md
hack/api-reference/registry.md
pkg/apis/registry/types.go
pkg/apis/registry/v1alpha3/types.go
pkg/apis/registry/v1alpha3/zz_generated.conversion.go
pkg/apis/registry/v1alpha3/zz_generated.deepcopy.go
pkg/apis/registry/validation/validation.go
pkg/apis/registry/validation/validation_test.go
pkg/apis/registry/zz_generated.deepcopy.go
pkg/component/registrycaches/registry_caches.go
pkg/component/registrycaches/registry_caches_test.go
pkg/component/registrycacheservices/registry_cache_services.go
pkg/component/registrycacheservices/registry_cache_services_test.go
pkg/utils/registry/registry.go
pkg/utils/registry/registry_test.go
skaffold-operator.yaml
skaffold.yaml
test/e2e/cache/create_enabled_force_delete.go

/area usability
This PR adds a new configuration option: "serviceNameSuffix".
This option allows to customize the service name after the `registry-` part.
I chose to only allow customization of the suffix as we prob. don't want to allow users specifying the service name as something like "kube-dns".
See mentioned issue for potential use-cases.
Fixes https://github.com/gardener/gardener-extension-registry-cache/issues/402
```feature user
The registry-cache service name can now be customized with the `serviceNameSuffix` option.
```

Allow configuring registry cache service name

---

pkg/component/registrycaches/monitoring.go

/area monitoring
/kind bug
Lower-case roles are not valid for a while anymore and did just work because of an workaround in Gardener which has been removed recently (see https://github.com/gardener/gardener/pull/12908).
This PR updates one role we forgot earlier. 
Part of https://github.com/gardener/gardener/issues/12401
```bugfix operator
The `Endpoints` role in monitoring `ScrapeConfig` has been fixed.
```

Fix monitoring `ScrapeConfig` roles

---

pkg/apis/registry/validation/validation.go
pkg/apis/registry/validation/validation_test.go
pkg/component/registrycaches/registry_caches.go
pkg/component/registrycaches/registry_caches_test.go

/area quality
Removes the `spec.serviceName` form the registry `StatefulSet` as the `$(podname).$(governing service domain)` DNS records are not used and do not need to be managed by the controller.
The `revisionHistoryLimit=2` field is added to registry `StatefulSet` spec - ref #378.
Fixes #378
```breaking user
Registry cache Pods are no longer reachable using Pod DNS - `$(podname).$(governing service domain)`, for example `registry-docker-io-0.registry-docker-io.kube-system.svc.cluster.local`.
```
```other operator
The `spec.serviceName` field has been removed from the registry cache StatefulSet. All registry …
```

Remove `spec.serviceName` and add `spec.revisionHistoryLimit=2` fields in the registry `StatefulSet`

---

.github/workflows/build.yaml

/area delivery
/kind bug
Setup git identity for `run-linter` GitHub action
Currently the release build fails with:
```
fatal: empty ident name (for <runner@runnervm...>) not allowed
make: *** [Makefile:70: check-generate] Error 128
Error: Process completed with exit code 2.
```
Fixes #
```other operator
NONE
```

Set up git identity for `run-linter` GitHub action
